name: toko_ecommerce
description: A simple e-commerce demo using fakestoreapi
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1
  provider: ^6.0.6
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.6